# Generated by Django 4.2.4 on 2023-08-14 07:41

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(choices=[(None, 'Select currency'), ('ALL', 'ALL'), ('AFN', 'AFN'), ('ARS', 'ARS'), ('AWG', 'AWG'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BSD', 'BSD'), ('BBD', 'BBD'), ('BDT', 'BDT'), ('BYR', 'BYR'), ('BZD', 'BZD'), ('BMD', 'BMD'), ('BOB', 'BOB'), ('BAM', 'BAM'), ('BWP', 'BWP'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BND', 'BND'), ('KHR', 'KHR'), ('CAD', 'CAD'), ('KYD', 'KYD'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('HRK', 'HRK'), ('CUP', 'CUP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('XCD', 'XCD'), ('EGP', 'EGP'), ('SVC', 'SVC'), ('EEK', 'EEK'), ('EUR', 'EUR'), ('FKP', 'FKP'), ('FJD', 'FJD'), ('GHC', 'GHC'), ('GIP', 'GIP'), ('GTQ', 'GTQ'), ('GGP', 'GGP'), ('GYD', 'GYD'), ('HNL', 'HNL'), ('HKD', 'HKD'), ('HUF', 'HUF'), ('ISK', 'ISK'), ('INR', 'INR'), ('IDR', 'IDR'), ('IRR', 'IRR'), ('IMP', 'IMP'), ('ILS', 'ILS'), ('JMD', 'JMD'), ('JPY', 'JPY'), ('JEP', 'JEP'), ('KZT', 'KZT'), ('KPW', 'KPW'), ('KRW', 'KRW'), ('KGS', 'KGS'), ('LAK', 'LAK'), ('LVL', 'LVL'), ('LBP', 'LBP'), ('LRD', 'LRD'), ('LTL', 'LTL'), ('MKD', 'MKD'), ('MYR', 'MYR'), ('MUR', 'MUR'), ('MXN', 'MXN'), ('MNT', 'MNT'), ('MZN', 'MZN'), ('NAD', 'NAD'), ('NPR', 'NPR'), ('ANG', 'ANG'), ('NZD', 'NZD'), ('NIO', 'NIO'), ('NGN', 'NGN'), ('NOK', 'NOK'), ('OMR', 'OMR'), ('PKR', 'PKR'), ('PAB', 'PAB'), ('PYG', 'PYG'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PLN', 'PLN'), ('QAR', 'QAR'), ('RON', 'RON'), ('SHP', 'SHP'), ('SAR', 'SAR'), ('RSD', 'RSD'), ('SCR', 'SCR'), ('SGD', 'SGD'), ('SBD', 'SBD'), ('SOS', 'SOS'), ('ZAR', 'ZAR'), ('LKR', 'LKR'), ('SEK', 'SEK'), ('CHF', 'CHF'), ('SRD', 'SRD'), ('SYP', 'SYP'), ('TWD', 'TWD'), ('THB', 'THB'), ('TTD', 'TTD'), ('TRY', 'TRY'), ('TRL', 'TRL'), ('TVD', 'TVD'), ('UAH', 'UAH'), ('GBP', 'GBP'), ('USD', 'USD'), ('UYU', 'UYU'), ('UZS', 'UZS'), ('VEF', 'VEF'), ('VND', 'VND'), ('YER', 'YER'), ('ZWD', 'ZWD')], default='DEFAULT', max_length=15)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('category_type', models.CharField(choices=[(None, 'Select category type'), ('Income', 'Income'), ('Expense', 'Expense')], default=(None, 'Select category type'), max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
