# Generated by Django 4.2.4 on 2023-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('ALL', 'ALL'), ('AFN', 'AFN'), ('ARS', 'ARS'), ('AWG', 'AWG'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BSD', 'BSD'), ('BBD', 'BBD'), ('BDT', 'BDT'), ('BYR', 'BYR'), ('BZD', 'BZD'), ('BMD', 'BMD'), ('BOB', 'BOB'), ('BAM', 'BAM'), ('BWP', 'BWP'), ('BGN', 'BGN'), ('BRL', 'BRL'), ('BND', 'BND'), ('KHR', 'KHR'), ('CAD', 'CAD'), ('KYD', 'KYD'), ('CLP', 'CLP'), ('CNY', 'CNY'), ('COP', 'COP'), ('CRC', 'CRC'), ('HRK', 'HRK'), ('CUP', 'CUP'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DOP', 'DOP'), ('XCD', 'XCD'), ('EGP', 'EGP'), ('SVC', 'SVC'), ('EEK', 'EEK'), ('EUR', 'EUR'), ('FKP', 'FKP'), ('FJD', 'FJD'), ('GHC', 'GHC'), ('GIP', 'GIP'), ('GTQ', 'GTQ'), ('GGP', 'GGP'), ('GYD', 'GYD'), ('HNL', 'HNL'), ('HKD', 'HKD'), ('HUF', 'HUF'), ('ISK', 'ISK'), ('INR', 'INR'), ('IDR', 'IDR'), ('IRR', 'IRR'), ('IMP', 'IMP'), ('ILS', 'ILS'), ('JMD', 'JMD'), ('JPY', 'JPY'), ('JEP', 'JEP'), ('KZT', 'KZT'), ('KPW', 'KPW'), ('KRW', 'KRW'), ('KGS', 'KGS'), ('LAK', 'LAK'), ('LVL', 'LVL'), ('LBP', 'LBP'), ('LRD', 'LRD'), ('LTL', 'LTL'), ('MKD', 'MKD'), ('MYR', 'MYR'), ('MUR', 'MUR'), ('MXN', 'MXN'), ('MNT', 'MNT'), ('MZN', 'MZN'), ('NAD', 'NAD'), ('NPR', 'NPR'), ('ANG', 'ANG'), ('NZD', 'NZD'), ('NIO', 'NIO'), ('NGN', 'NGN'), ('NOK', 'NOK'), ('OMR', 'OMR'), ('PKR', 'PKR'), ('PAB', 'PAB'), ('PYG', 'PYG'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PLN', 'PLN'), ('QAR', 'QAR'), ('RON', 'RON'), ('SHP', 'SHP'), ('SAR', 'SAR'), ('RSD', 'RSD'), ('SCR', 'SCR'), ('SGD', 'SGD'), ('SBD', 'SBD'), ('SOS', 'SOS'), ('ZAR', 'ZAR'), ('LKR', 'LKR'), ('SEK', 'SEK'), ('CHF', 'CHF'), ('SRD', 'SRD'), ('SYP', 'SYP'), ('TWD', 'TWD'), ('THB', 'THB'), ('TTD', 'TTD'), ('TRY', 'TRY'), ('TRL', 'TRL'), ('TVD', 'TVD'), ('UAH', 'UAH'), ('GBP', 'GBP'), ('USD', 'USD'), ('UYU', 'UYU'), ('UZS', 'UZS'), ('VEF', 'VEF'), ('VND', 'VND'), ('YER', 'YER'), ('ZWD', 'ZWD')], max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=7),
        ),
    ]
